import math
from pathlib import Path

BALL_RADIUS = 3
BALL_RADIUS_PHOTO = 20  
POCKET_MARGIN=60
WALL_MARGIN=100

BALL_SPACING = BALL_RADIUS * 2.2
TABLE_LENGTH = 290
TABLE_WIDTH = 145

CORNER_POCKET_RADIUS = 4
SIDE_POCKET_RADIUS = 4.5
ADD_TO_POCKET = 3.5

SAFE_DISTANCE = BALL_RADIUS * 0.5

WEIGHT_WHITE_TO_TARGET = 1 / (TABLE_LENGTH / 2)
WEIGHT_TARGET_TO_POCKET = 1 / (TABLE_LENGTH / 4)

MAX_WHITE_TO_TARGET = TABLE_LENGTH / 2
MAX_TARGET_TO_POCKET = math.hypot(TABLE_LENGTH, TABLE_WIDTH) / 2

NOT_FREE_SHOT = "dont have a free shot"

OUTPUT_JSON_PATH = "photos/output/img_JSON.json"
OUTPUT_IMAGE_PATH = Path("photos/output/img.png")
OUTPUT_CONTACT_VIEW_PATH = Path("photos/output/img_contact.png")

FORSE_WALL_SHOT = False

CROP_HALF_SIZE = 60
